// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/greboid/puzzad/ent/access"
	"github.com/greboid/puzzad/ent/adventure"
	"github.com/greboid/puzzad/ent/predicate"
	"github.com/greboid/puzzad/ent/team"
)

// AccessUpdate is the builder for updating Access entities.
type AccessUpdate struct {
	config
	hooks    []Hook
	mutation *AccessMutation
}

// Where appends a list predicates to the AccessUpdate builder.
func (au *AccessUpdate) Where(ps ...predicate.Access) *AccessUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetStatus sets the "status" field.
func (au *AccessUpdate) SetStatus(a access.Status) *AccessUpdate {
	au.mutation.SetStatus(a)
	return au
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (au *AccessUpdate) SetNillableStatus(a *access.Status) *AccessUpdate {
	if a != nil {
		au.SetStatus(*a)
	}
	return au
}

// SetCode sets the "code" field.
func (au *AccessUpdate) SetCode(s string) *AccessUpdate {
	au.mutation.SetCode(s)
	return au
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (au *AccessUpdate) SetNillableCode(s *string) *AccessUpdate {
	if s != nil {
		au.SetCode(*s)
	}
	return au
}

// SetTeamID sets the "team_id" field.
func (au *AccessUpdate) SetTeamID(i int) *AccessUpdate {
	au.mutation.SetTeamID(i)
	return au
}

// SetAdventureID sets the "adventure_id" field.
func (au *AccessUpdate) SetAdventureID(i int) *AccessUpdate {
	au.mutation.SetAdventureID(i)
	return au
}

// SetTeam sets the "team" edge to the Team entity.
func (au *AccessUpdate) SetTeam(t *Team) *AccessUpdate {
	return au.SetTeamID(t.ID)
}

// SetAdventuresID sets the "adventures" edge to the Adventure entity by ID.
func (au *AccessUpdate) SetAdventuresID(id int) *AccessUpdate {
	au.mutation.SetAdventuresID(id)
	return au
}

// SetAdventures sets the "adventures" edge to the Adventure entity.
func (au *AccessUpdate) SetAdventures(a *Adventure) *AccessUpdate {
	return au.SetAdventuresID(a.ID)
}

// Mutation returns the AccessMutation object of the builder.
func (au *AccessUpdate) Mutation() *AccessMutation {
	return au.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (au *AccessUpdate) ClearTeam() *AccessUpdate {
	au.mutation.ClearTeam()
	return au
}

// ClearAdventures clears the "adventures" edge to the Adventure entity.
func (au *AccessUpdate) ClearAdventures() *AccessUpdate {
	au.mutation.ClearAdventures()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccessUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		if err = au.check(); err != nil {
			return 0, err
		}
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = au.check(); err != nil {
				return 0, err
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccessUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccessUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccessUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AccessUpdate) check() error {
	if v, ok := au.mutation.Status(); ok {
		if err := access.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Access.status": %w`, err)}
		}
	}
	if _, ok := au.mutation.TeamID(); au.mutation.TeamCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Access.team"`)
	}
	if _, ok := au.mutation.AdventuresID(); au.mutation.AdventuresCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Access.adventures"`)
	}
	return nil
}

func (au *AccessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   access.Table,
			Columns: access.Columns,
			CompositeID: []*sqlgraph.FieldSpec{
				{
					Type:   field.TypeInt,
					Column: access.FieldTeamID,
				},
				{
					Type:   field.TypeInt,
					Column: access.FieldAdventureID,
				},
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: access.FieldStatus,
		})
	}
	if value, ok := au.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: access.FieldCode,
		})
	}
	if au.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   access.TeamTable,
			Columns: []string{access.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: team.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   access.TeamTable,
			Columns: []string{access.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: team.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.AdventuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   access.AdventuresTable,
			Columns: []string{access.AdventuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adventure.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.AdventuresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   access.AdventuresTable,
			Columns: []string{access.AdventuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adventure.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{access.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AccessUpdateOne is the builder for updating a single Access entity.
type AccessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessMutation
}

// SetStatus sets the "status" field.
func (auo *AccessUpdateOne) SetStatus(a access.Status) *AccessUpdateOne {
	auo.mutation.SetStatus(a)
	return auo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (auo *AccessUpdateOne) SetNillableStatus(a *access.Status) *AccessUpdateOne {
	if a != nil {
		auo.SetStatus(*a)
	}
	return auo
}

// SetCode sets the "code" field.
func (auo *AccessUpdateOne) SetCode(s string) *AccessUpdateOne {
	auo.mutation.SetCode(s)
	return auo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (auo *AccessUpdateOne) SetNillableCode(s *string) *AccessUpdateOne {
	if s != nil {
		auo.SetCode(*s)
	}
	return auo
}

// SetTeamID sets the "team_id" field.
func (auo *AccessUpdateOne) SetTeamID(i int) *AccessUpdateOne {
	auo.mutation.SetTeamID(i)
	return auo
}

// SetAdventureID sets the "adventure_id" field.
func (auo *AccessUpdateOne) SetAdventureID(i int) *AccessUpdateOne {
	auo.mutation.SetAdventureID(i)
	return auo
}

// SetTeam sets the "team" edge to the Team entity.
func (auo *AccessUpdateOne) SetTeam(t *Team) *AccessUpdateOne {
	return auo.SetTeamID(t.ID)
}

// SetAdventuresID sets the "adventures" edge to the Adventure entity by ID.
func (auo *AccessUpdateOne) SetAdventuresID(id int) *AccessUpdateOne {
	auo.mutation.SetAdventuresID(id)
	return auo
}

// SetAdventures sets the "adventures" edge to the Adventure entity.
func (auo *AccessUpdateOne) SetAdventures(a *Adventure) *AccessUpdateOne {
	return auo.SetAdventuresID(a.ID)
}

// Mutation returns the AccessMutation object of the builder.
func (auo *AccessUpdateOne) Mutation() *AccessMutation {
	return auo.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (auo *AccessUpdateOne) ClearTeam() *AccessUpdateOne {
	auo.mutation.ClearTeam()
	return auo
}

// ClearAdventures clears the "adventures" edge to the Adventure entity.
func (auo *AccessUpdateOne) ClearAdventures() *AccessUpdateOne {
	auo.mutation.ClearAdventures()
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccessUpdateOne) Select(field string, fields ...string) *AccessUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Access entity.
func (auo *AccessUpdateOne) Save(ctx context.Context) (*Access, error) {
	var (
		err  error
		node *Access
	)
	if len(auo.hooks) == 0 {
		if err = auo.check(); err != nil {
			return nil, err
		}
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = auo.check(); err != nil {
				return nil, err
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, auo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Access)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AccessMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccessUpdateOne) SaveX(ctx context.Context) *Access {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccessUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccessUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AccessUpdateOne) check() error {
	if v, ok := auo.mutation.Status(); ok {
		if err := access.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Access.status": %w`, err)}
		}
	}
	if _, ok := auo.mutation.TeamID(); auo.mutation.TeamCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Access.team"`)
	}
	if _, ok := auo.mutation.AdventuresID(); auo.mutation.AdventuresCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Access.adventures"`)
	}
	return nil
}

func (auo *AccessUpdateOne) sqlSave(ctx context.Context) (_node *Access, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   access.Table,
			Columns: access.Columns,
			CompositeID: []*sqlgraph.FieldSpec{
				{
					Type:   field.TypeInt,
					Column: access.FieldTeamID,
				},
				{
					Type:   field.TypeInt,
					Column: access.FieldAdventureID,
				},
			},
		},
	}
	if id, ok := auo.mutation.TeamID(); !ok {
		return nil, &ValidationError{Name: "team_id", err: errors.New(`ent: missing "Access.team_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := auo.mutation.AdventureID(); !ok {
		return nil, &ValidationError{Name: "adventure_id", err: errors.New(`ent: missing "Access.adventure_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !access.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: access.FieldStatus,
		})
	}
	if value, ok := auo.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: access.FieldCode,
		})
	}
	if auo.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   access.TeamTable,
			Columns: []string{access.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: team.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   access.TeamTable,
			Columns: []string{access.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: team.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.AdventuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   access.AdventuresTable,
			Columns: []string{access.AdventuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adventure.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.AdventuresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   access.AdventuresTable,
			Columns: []string{access.AdventuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adventure.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Access{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{access.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
