// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/greboid/puzzad/ent/adventure"
	"github.com/greboid/puzzad/ent/predicate"
	"github.com/greboid/puzzad/ent/puzzle"
)

// PuzzleUpdate is the builder for updating Puzzle entities.
type PuzzleUpdate struct {
	config
	hooks    []Hook
	mutation *PuzzleMutation
}

// Where appends a list predicates to the PuzzleUpdate builder.
func (pu *PuzzleUpdate) Where(ps ...predicate.Puzzle) *PuzzleUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetTitle sets the "title" field.
func (pu *PuzzleUpdate) SetTitle(s string) *PuzzleUpdate {
	pu.mutation.SetTitle(s)
	return pu
}

// SetAnswer sets the "answer" field.
func (pu *PuzzleUpdate) SetAnswer(s string) *PuzzleUpdate {
	pu.mutation.SetAnswer(s)
	return pu
}

// SetOrder sets the "order" field.
func (pu *PuzzleUpdate) SetOrder(i int) *PuzzleUpdate {
	pu.mutation.ResetOrder()
	pu.mutation.SetOrder(i)
	return pu
}

// AddOrder adds i to the "order" field.
func (pu *PuzzleUpdate) AddOrder(i int) *PuzzleUpdate {
	pu.mutation.AddOrder(i)
	return pu
}

// SetAdventureID sets the "adventure" edge to the Adventure entity by ID.
func (pu *PuzzleUpdate) SetAdventureID(id int) *PuzzleUpdate {
	pu.mutation.SetAdventureID(id)
	return pu
}

// SetNillableAdventureID sets the "adventure" edge to the Adventure entity by ID if the given value is not nil.
func (pu *PuzzleUpdate) SetNillableAdventureID(id *int) *PuzzleUpdate {
	if id != nil {
		pu = pu.SetAdventureID(*id)
	}
	return pu
}

// SetAdventure sets the "adventure" edge to the Adventure entity.
func (pu *PuzzleUpdate) SetAdventure(a *Adventure) *PuzzleUpdate {
	return pu.SetAdventureID(a.ID)
}

// Mutation returns the PuzzleMutation object of the builder.
func (pu *PuzzleUpdate) Mutation() *PuzzleMutation {
	return pu.mutation
}

// ClearAdventure clears the "adventure" edge to the Adventure entity.
func (pu *PuzzleUpdate) ClearAdventure() *PuzzleUpdate {
	pu.mutation.ClearAdventure()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PuzzleUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PuzzleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			if pu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PuzzleUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PuzzleUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PuzzleUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PuzzleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   puzzle.Table,
			Columns: puzzle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: puzzle.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: puzzle.FieldTitle,
		})
	}
	if value, ok := pu.mutation.Answer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: puzzle.FieldAnswer,
		})
	}
	if value, ok := pu.mutation.Order(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: puzzle.FieldOrder,
		})
	}
	if value, ok := pu.mutation.AddedOrder(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: puzzle.FieldOrder,
		})
	}
	if pu.mutation.AdventureCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   puzzle.AdventureTable,
			Columns: []string{puzzle.AdventureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adventure.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.AdventureIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   puzzle.AdventureTable,
			Columns: []string{puzzle.AdventureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adventure.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{puzzle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PuzzleUpdateOne is the builder for updating a single Puzzle entity.
type PuzzleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PuzzleMutation
}

// SetTitle sets the "title" field.
func (puo *PuzzleUpdateOne) SetTitle(s string) *PuzzleUpdateOne {
	puo.mutation.SetTitle(s)
	return puo
}

// SetAnswer sets the "answer" field.
func (puo *PuzzleUpdateOne) SetAnswer(s string) *PuzzleUpdateOne {
	puo.mutation.SetAnswer(s)
	return puo
}

// SetOrder sets the "order" field.
func (puo *PuzzleUpdateOne) SetOrder(i int) *PuzzleUpdateOne {
	puo.mutation.ResetOrder()
	puo.mutation.SetOrder(i)
	return puo
}

// AddOrder adds i to the "order" field.
func (puo *PuzzleUpdateOne) AddOrder(i int) *PuzzleUpdateOne {
	puo.mutation.AddOrder(i)
	return puo
}

// SetAdventureID sets the "adventure" edge to the Adventure entity by ID.
func (puo *PuzzleUpdateOne) SetAdventureID(id int) *PuzzleUpdateOne {
	puo.mutation.SetAdventureID(id)
	return puo
}

// SetNillableAdventureID sets the "adventure" edge to the Adventure entity by ID if the given value is not nil.
func (puo *PuzzleUpdateOne) SetNillableAdventureID(id *int) *PuzzleUpdateOne {
	if id != nil {
		puo = puo.SetAdventureID(*id)
	}
	return puo
}

// SetAdventure sets the "adventure" edge to the Adventure entity.
func (puo *PuzzleUpdateOne) SetAdventure(a *Adventure) *PuzzleUpdateOne {
	return puo.SetAdventureID(a.ID)
}

// Mutation returns the PuzzleMutation object of the builder.
func (puo *PuzzleUpdateOne) Mutation() *PuzzleMutation {
	return puo.mutation
}

// ClearAdventure clears the "adventure" edge to the Adventure entity.
func (puo *PuzzleUpdateOne) ClearAdventure() *PuzzleUpdateOne {
	puo.mutation.ClearAdventure()
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PuzzleUpdateOne) Select(field string, fields ...string) *PuzzleUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Puzzle entity.
func (puo *PuzzleUpdateOne) Save(ctx context.Context) (*Puzzle, error) {
	var (
		err  error
		node *Puzzle
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PuzzleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			if puo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = puo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, puo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Puzzle)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PuzzleMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PuzzleUpdateOne) SaveX(ctx context.Context) *Puzzle {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PuzzleUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PuzzleUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PuzzleUpdateOne) sqlSave(ctx context.Context) (_node *Puzzle, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   puzzle.Table,
			Columns: puzzle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: puzzle.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Puzzle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, puzzle.FieldID)
		for _, f := range fields {
			if !puzzle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != puzzle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: puzzle.FieldTitle,
		})
	}
	if value, ok := puo.mutation.Answer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: puzzle.FieldAnswer,
		})
	}
	if value, ok := puo.mutation.Order(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: puzzle.FieldOrder,
		})
	}
	if value, ok := puo.mutation.AddedOrder(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: puzzle.FieldOrder,
		})
	}
	if puo.mutation.AdventureCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   puzzle.AdventureTable,
			Columns: []string{puzzle.AdventureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adventure.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.AdventureIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   puzzle.AdventureTable,
			Columns: []string{puzzle.AdventureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adventure.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Puzzle{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{puzzle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
