// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/greboid/puzzad/ent/guess"
	"github.com/greboid/puzzad/ent/schema"
	"github.com/greboid/puzzad/ent/team"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	guessFields := schema.Guess{}.Fields()
	_ = guessFields
	// guessDescSubmitted is the schema descriptor for submitted field.
	guessDescSubmitted := guessFields[1].Descriptor()
	// guess.DefaultSubmitted holds the default value on creation for the submitted field.
	guess.DefaultSubmitted = guessDescSubmitted.Default.(time.Time)
	teamMixin := schema.Team{}.Mixin()
	teamMixinFields0 := teamMixin[0].Fields()
	_ = teamMixinFields0
	teamFields := schema.Team{}.Fields()
	_ = teamFields
	// teamDescCreateTime is the schema descriptor for create_time field.
	teamDescCreateTime := teamMixinFields0[0].Descriptor()
	// team.DefaultCreateTime holds the default value on creation for the create_time field.
	team.DefaultCreateTime = teamDescCreateTime.Default.(func() time.Time)
	// teamDescName is the schema descriptor for name field.
	teamDescName := teamFields[0].Descriptor()
	// team.NameValidator is a validator for the "name" field. It is called by the builders before save.
	team.NameValidator = func() func(string) error {
		validators := teamDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// teamDescCode is the schema descriptor for code field.
	teamDescCode := teamFields[1].Descriptor()
	// team.DefaultCode holds the default value on creation for the code field.
	team.DefaultCode = teamDescCode.Default.(func() string)
}
