// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/greboid/puzzad/ent/access"
	"github.com/greboid/puzzad/ent/guess"
	"github.com/greboid/puzzad/ent/user"
	"github.com/greboid/puzzad/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accessFields := schema.Access{}.Fields()
	_ = accessFields
	// accessDescCode is the schema descriptor for code field.
	accessDescCode := accessFields[1].Descriptor()
	// access.DefaultCode holds the default value on creation for the code field.
	access.DefaultCode = accessDescCode.Default.(func() string)
	// access.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	access.CodeValidator = accessDescCode.Validators[0].(func(string) error)
	guessMixin := schema.Guess{}.Mixin()
	guessMixinFields0 := guessMixin[0].Fields()
	_ = guessMixinFields0
	guessFields := schema.Guess{}.Fields()
	_ = guessFields
	// guessDescCreateTime is the schema descriptor for create_time field.
	guessDescCreateTime := guessMixinFields0[0].Descriptor()
	// guess.DefaultCreateTime holds the default value on creation for the create_time field.
	guess.DefaultCreateTime = guessDescCreateTime.Default.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescVerifyCode is the schema descriptor for verifyCode field.
	userDescVerifyCode := userFields[0].Descriptor()
	// user.DefaultVerifyCode holds the default value on creation for the verifyCode field.
	user.DefaultVerifyCode = userDescVerifyCode.Default.(func() string)
	// userDescVerifyExpiry is the schema descriptor for verifyExpiry field.
	userDescVerifyExpiry := userFields[1].Descriptor()
	// user.DefaultVerifyExpiry holds the default value on creation for the verifyExpiry field.
	user.DefaultVerifyExpiry = userDescVerifyExpiry.Default.(func() time.Time)
}
