// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Access is the predicate function for access builders.
type Access func(*sql.Selector)

// Adventure is the predicate function for adventure builders.
type Adventure func(*sql.Selector)

// Guess is the predicate function for guess builders.
type Guess func(*sql.Selector)

// Progress is the predicate function for progress builders.
type Progress func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
