// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Adventure is the predicate function for adventure builders.
type Adventure func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// Guess is the predicate function for guess builders.
type Guess func(*sql.Selector)

// Progress is the predicate function for progress builders.
type Progress func(*sql.Selector)

// Puzzle is the predicate function for puzzle builders.
type Puzzle func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
